### PR TITLE
fix remove attr suffix

### PR DESCRIPTION
**Pull request by shoota**
Close https://github.com/claudetech/node-static-i18n/issues/27

### CODE REVIEW

**Comment by tuvistavie** [comment]
Thank you very much!

**Comment by heavenshell** [comment]
@tuvistavie Please release this to npm 😢

**Comment by tuvistavie** [comment]
I just published to npm as 0.2.2

**Comment by heavenshell** [comment]
Thank you!!!!

**Comment by shoota** [comment]
Thanks for the release!!! 🚀

**Pull request merged**
