### PR TITLE
Fix style's urls (issue #38)

### PR DESCRIPTION
**Pull request by adrienluitot**
Fixed issue #38.

I don't know if it's okay for you, I made something a bit tricky, maybe it does not correspond to what you would like ?
I edited the index.html file in the test folder so you can test the result.

### CODE REVIEW

**Comment by adrienluitot** [comment]
I think I did what you asked. Tell me if there is anything to change!

**Review by danhper — APPROVED** [review]
Looks great, thanks a lot!!

**Comment by danhper** [comment]
I just pushed a new version to npm with your changes, thanks again!

**Comment by adrienluitot** [comment]
Nice :D 
My pleasure ;)

**Pull request merged**
